### ISSUE TITLE
The following links are not working. 

### ISSUE THREAD

**Issue by sreekzz** [Azure/HDInsight#11]
The following Links are not working. 

[HDInsight 5.x component versions](https://github.com/Azure/HDInsight/blob/2023-09-12/hdinsight-5x-component-versioning.md)
[HDInsight 4.x component versions](https://github.com/Azure/HDInsight/blob/2023-09-12/hdinsight-40-component-versioning.md)

Please refer to the release notes of May 12, 2023 for the correct links foe the above, and update the link accordingly.

**Comment by v-akarnase** [comment]
Resolved
