### ISSUE TITLE
Any potential roadmap on Azure HDInsight Spark 3.3.4 Version

### ISSUE THREAD

**Issue by rizahmedk** [Azure/HDInsight#12]
Hi Team,

Any potential roadmap on Azure HDInsight Spark 3.3.4 Version

**Comment by sreekzz** [comment]
@rizahmedk , Thanks for reaching out to us. I have asked the concerned PM to look into this. Will get back to you once I hear from him.

**Comment by abhishjain002** [comment]
Spark 3.3 is already available in HDInsight and we plan to upgrade next to Spark 3.5 tentatively in H2 of calendar year 2025.

**Comment by dbeavon** [comment]
> Spark 3.3 is already available in HDInsight and we plan to upgrade next to Spark 3.5 tentatively in H2 of calendar year 2025.

@abhishjain002 Are you still planning to upgrade to Spark 3.5?

Microsoft killed the AKS version of HDInsight, and I'm sincerely nervous that they will kill HDInsight altogether.
See here as well:
https://github.com/Azure/HDInsight/issues/15
