### ISSUE TITLE
Minor issue with links from Spark UI to SparkHistory/logs

### ISSUE THREAD

**Issue by dbeavon** [Azure/HDInsight#13]
I was told I can use this community to share a known bug.

There is a bug where the hdinsight spark ui is generating http 500.50 - TrackingID#2411150040009424.  It happens when clicking links to stderr and stdout, for a given executor.

This issue seems to be caused by malformed links.  It only happens after a node has been **removed** from the cluster.  Any nodes that are still living are not impacted.  You can actually retrieve logs for **both** types of nodes (living and removed), but you are forced to compose the URL **manually** after the node has been removed from the cluster.

This case has both a SR and an ICM.  I spoke with an engineer in the HDI team who thinks this issue may take more than a month to fix.  So I'm closing the SR for now, and will track the bug here instead.

**Comment by dbeavon** [comment]
More info:

Regardless of whether the executors and VM's are still running or not, it should be possible to get the logs

My understanding is that the log URL on the Spark history server UI will redirect you to the MapReduce history server.  This should not depend on whether the underlying agents are still living.
 
![Image](https://github.com/user-attachments/assets/6bc8deca-5228-48d7-80ce-b86598b8867d)





https://downloads.apache.org/spark/docs/3.1.1/running-on-yarn.html#:~:text=The%20logs%20are,the%20aggregated%20logs

**Comment by dbeavon** [comment]
Someone will have to confirm, but there should be an ICM that identifies this issue (at Microsoft) 

_This info may be more helpful than my customer-specific SR number...  I think my SR number is probably not very portable and, in any case, Microsoft should not be forcing customers to use reference numbers that can be tied back to them.  It is Microsoft's bug, after all, and it doesn't matter which customer has run into it first !_


The title of the ICM is "HDInsight Spark UI Gateway Issue," and it was created on November 24, 2024.

**Comment by sreekzz** [comment]
@dbeavon, Thanks for reaching out to us. I have asked the concerned PM to look into this. Will get back to you once I hear from him.

**Comment by dbeavon** [comment]
Thanks @sreekzz ,  this one affects us on a daily basis.  I'm guessing it affects other customers as well, although to a **lesser degree** if their clusters are not scaling up and down regularly as ours tend to do. 

I'm fairly certain this was a recent regression (we initiated our recent upgrade to v.5.1 from v.5.0 this year;  additionally we noticed that Microsoft has had some software releases, and they have been introducing some network-related changes to the product.)

**Comment by sreekzz** [comment]
As there is an ICM already existing, the support team will resolve this issue.
