### ISSUE TITLE
Issue with links to application master for Spark.  Happens in the yarn RM portal for HDI 5.1.6.7

### ISSUE THREAD

**Issue by dbeavon** [Azure/HDInsight#14]
I have a minor issue where links from the yarn RM portal are not formed properly, and it is preventing the Spark UI (application master) from being opened.

According to my interactions with Mindtree and Microsoft, this is probably a regression bug in the HDI environment 5.1.6.7.  This was released in October 2024.

I am putting notes about the bug here, for the sake of tracking.  The bug was opened as an SR:
"Hdinsight links in yarn portal are not properly formatted -  Tracking ID #2411230040000281"

This case has both a SR and an ICM. I spoke with an engineer in the HDI team who thinks this issue may take longer than a month to get a fix. So I'm closing the SR for now, but will periodically check with my contact at the PG to get updates.

FYI, I was told that this is probably a bug in the proprietary gateway of HDInsight.  There is a fairly easy workaround. If the URL for the application ID is not available, then we can simply click on the "app attempt" and find a better URL on that other screen.  It isn't clear why one of these screens provides a valid link to the spark application and the other does not.  More updates to follow...

**Comment by dbeavon** [comment]
More info:
The bug did not seem to happen in the prior version of the cluster:
"5.1.5.6". 

It is possible that the bug is specific to running HDI inside a vnet.

**Comment by dbeavon** [comment]
Hi @sreekzz .  There is an SR# and an ICM# as well.  I'm trying to reach an FTE to get the ICM for you.

I was told there will be some gateway changes being deployed in Feb.  Do you think that is a reasonable timeframe for a fix?

**Comment by sreekzz** [comment]
@dbeavon , Thanks for reaching out to us. I have asked the concerned PM to look into this. Will get back to you once I hear from him.

**Comment by dbeavon** [comment]
@sreekzz I'm working with an FTE, initials M.F.  He also said he would talk to a PM as well.  But the communication channels are pretty poor (via "professional/Mindtree" etc...) The loop was not closed.  
... I don't think it is a commitment but he initially said these bugs could be fixed by Feb,  

There are two bugs.  This current one is the less important of the two.  

(The other one that I posted in the issues list is more painful, in that it prevents me from opening my spark UI logs via the yarn history log service.  Even if the spark batch completed just 10 mins ago.  The only workaround is to sign into ssh, and run the yarn logs command on the head nodes.)

Both of these HDI gateway bugs are worth fixing.  I believe that both were a recent regression (breaking changes in the implementation of the HDI gateway between v.5 and v.5.1.).  I don't think the code running in the gateway is open source, but I'm guessing that both of these bugs would be very easy to fix.  I was able to "manually" format my own url's whenever the ones in yarn or spark ui are misbehaving, but it is a pretty _unnatural_ workaround (and probably not something that Microsoft would actually support in the long run, unlike the "**yarn logs"** in ssh).

Please let me know about your interaction with your PM.  Please propose that to the PM that Microsoft could publish a reference document with the known bugs.  At the time when I close a support case at Mindtree, I think **everything** is closed (the SR# and ICM# and all recollection of the bug I encountered).  Customers do not have any permanent reference to their issue that can be tracked over time.  Many bugs in Azure take months or years to fix, and customers **don't want to reopen the same bug** every six months, basically starting from scratch each time.

**Comment by sreekzz** [comment]
As there is an ICM already existing, the support team will resolve this issue.

**Comment by dbeavon** [comment]
@sreekzz Yes, I shared the tracking number three weeks ago.

Did you talk to a PM?  The support team (via Mindtree) said that it would NOT be fixed immediately, as there is some sort of code freeze in the product.

Any bugs like this which are disruptive, and last for a long period of time (months)  are likely to affect your other users and customers as well.  Do you have a mechanism for updating the list of "known issues", to reflect the problem so that other customers won't duplicate the same efforts, and try to report the same bug, and get the same response from the PG that they cannot fix it right now? 

Here is the link:
https://learn.microsoft.com/en-us/azure/hdinsight/hdinsight-known-issues
