### ISSUE TITLE
Any potential GA date (or roadmap) on Azure HDInsight 5.1?

### ISSUE THREAD

**Issue by tomqwu** [Azure/HDInsight#7]

**Comment by yeturis** [comment]
Hi @tomqwu , We are working relentlessly to get the GA for HDInsight 5.1, and we should be doing this within the next 2 months, Please do reach out to our support for any further questions. Happy to hear from you and we look forward to continue engaging with you on https://learn.microsoft.com/en-us/answers/tags/168/azure-hdinsight and also please post your ideas on https://feedback.azure.com/d365community/forum/14770d6d-7626-ec11-b6e6-000d3a4f032c
